### ISSUE TITLE
Does not work for big .bin files

### ISSUE THREAD

**Issue by dipcore** [cosmicdan/Mstar_bintool#2]
Getting "Error Allocating Memory" error. It seems like the problem is in line #45
`$sFileContents = FileRead($hFile)`
There is a memory limit, my .bin is 917Mb

Can it be fixed ? Maybe to read the file by chunks ?

**Comment by cosmicdan** [comment]
As mentioned in my blog post, it is indeed limited by system memory. I can read bin files up to 1.2GB or so fine on my machine of 16GB RAM.

I would have to make significant changes to support systems with less RAM. This script is effectively "finished" as far as im concerned, i have no time or need to make more changes - in fact I am leaving the software engineering industry completely. Hope you understand.

AutoIt is not a difficult language at all, though - maybe someone else can improve on it.

On 30 Aug 2016, dipcore notifications@github.com wrote:

> Getting "Error Allocating Memory" error. It seems like the problem is
> in line #45
> `$sFileContents = FileRead($hFile)`
> There is a memory limit, my .bin is 917Mb
> 
> Can it be fixed ? Maybe to read the file by chunks ?

## 

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by dipcore** [comment]
I have 16GB RAM installed 
Can you try to unpack my .bin file just to make 100% sure it's something on my side? https://drive.google.com/drive/folders/0B9s5NUf528GlYVBMMzlYc3JxTjg (just rename it to MstarUpgrade.bin)

**Comment by dipcore** [comment]
I was able to localize and "solve" the problem, it's in _BinaryInBin function. That function contains DllStructCreate and DllStructSetData which cases the crash. So I have to run it in x64 mode to avoid memory allocation problem.
